### ISSUE TITLE
I made something wrong, but not sure where.

### ISSUE THREAD

**Issue by j2l** [steveseguin/color-grading#3]
Fantastic project to learn calibration @steveseguin, thank you!

I have a color reference card with known RGB values so I need exactly this project to make a correction LUT in OBS.
I shot a full size ref card with some slight perspective and it also have numbers. Maybe because of this, it doesn't see the first colors and I get more RGB values in histogram and computed LUT is incorrect .

Is there a way, in Step 4, to see/tweak which point/area it "sees" (uses)?
Here are my files enclosed to get an idea.
![wrong_card](https://user-images.githubusercontent.com/65325/222188433-d8e53f97-33e2-4ced-a3f4-ec4c4b92db1f.png)
![wrong_rgb](https://user-images.githubusercontent.com/65325/222188735-8267f8aa-de3f-4651-9425-30978a1e5892.png)
expected:
![expected](https://user-images.githubusercontent.com/65325/222190003-40dc1f9e-8750-4985-8576-af943dbe069b.png)

ref card
![ref_card_int](https://user-images.githubusercontent.com/65325/222188486-d6da14a6-e78a-4da8-8fd4-bd6c152a42b0.png)
![wrong](https://user-images.githubusercontent.com/65325/222188638-490bdc01-955e-4bcb-a6b1-6859c8c60422.png)
![wrong_lut](https://user-images.githubusercontent.com/65325/222188690-2578f76e-2019-4c45-a91a-e991dc34e27f.png)

**Comment by j2l** [comment]
I corrected the perspective and it keeps on wrongly interpreting the same colors (first 4 and first 3 greys).
![ref_card_int(1)](https://user-images.githubusercontent.com/65325/222193770-5c747157-f728-4d78-82ee-a934d4d178a8.png)

**Comment by j2l** [comment]
cropping more and saving as JPG seems to fix it for colors:
![ref_card_int](https://user-images.githubusercontent.com/65325/222199467-e539b7e7-f5d4-4a88-957f-1b9348e92f7f.jpg)
interpreted as:
![interpreted](https://user-images.githubusercontent.com/65325/222199554-6292de20-fd60-4b7f-b959-af2ac270f802.png)

But since color cards are usually with borders, a way to see/select areas is still needed (area to average noise, especially in low light).
Too bad I can't code in python, I'd love to improve it with an array of rectangle you could move manually.

BTW, it should be mandatory to upload a photo taken at the same moment to test the correction instead of using your pic since your camera and light condition is different from mine :)

**Comment by steveseguin** [comment]
Thank you for the feedback.  I can probably make a mode for color-cards that accounts for borders, or a way to select the points.  It might be easier for me to make that in Javascript, to pre-process the image, rather than in Python though.

> BTW, it should be mandatory to upload a photo taken at the same moment to test the correction instead of using your pic since your camera and light condition is different from mine :)

Yeah, definitely don't use my image if using your own color cards - that wouldn't make any sense.

**Comment by steveseguin** [comment]
I modified it a bit, adding a border-value option now. I have it pre-set to 25%, which should help I think in your case.

I also ran script with my own color card, and it turned out pretty okay:
https://github.com/steveseguin/color-grading/blob/master/spyder_24_color_card.ipynb

![image](https://user-images.githubusercontent.com/2575698/222240950-555ebf22-1ef0-4f80-ab30-a4a0052cae80.png)

![image](https://user-images.githubusercontent.com/2575698/222241070-d5753c03-7788-46e2-867d-23b2450f3072.png)

If there's still an issue with noise, I suppose I can add a denoiser , but a blur filter might also work.

**Comment by j2l** [comment]
Great! Thank you @steveseguin !!
Funny, looks like we have a mirror of each color card.

Your camera looks far better than mine though, histogram doesn't have more than the 3 RGB values, like I do.
Since I have this "noise" value on the left side, and it changed after i cropped, I guess I would need blur. I could add it when fixing the perspective.

I'll test it tomorrow, thank you again!

**Comment by steveseguin** [comment]
I bought my card directly from Datacolor; wasn't cheap of course, but since I bought it as a replacement card (without case), it was reasonable.

**Comment by j2l** [comment]
Histogram is now far better.
![good_histogram](https://user-images.githubusercontent.com/65325/222384529-9381c721-412b-42a0-849c-4fbec7e08760.png)
It works fine,  so I'm closing this ticket.

Thank you again for the fix and the overall quality of this project.
It encourages me to get a decent camera :smile:
